version: '3.8'

services:
    postgres:
        container_name: sensor-db
        image: postgres:14.0
        restart: always
        environment:
            POSTGRES_PASSWORD: "${PG_PASSWORD}"
            POSTGRES_DB: postgres
        volumes:
            - /db_data:/var/lib/postgresql/data
        ports:
            - 30432:5432
    server:
        container_name: sensor-backend
        build:
            context: .
        depends_on: [postgres]
        restart: always
        ports:
            - 8080:9090
        environment: 
            DATABASE_URL: "postgres://postgres:${PG_PASSWORD}@postgres:5432/postgres"
            REST_PORT: "${REST_PORT}"
            HIBOU_URL: "${HIBOU_URL}"
            HIBOU_CODE: "${HIBOU_CODE}"
            HIBOU_KEY: "${HIBOU_KEY}"
            HIBOU_APP: "${HIBOU_APP}"