name: docker-deploy
run-name: ${{ github.actor }} is deploying with docker
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: production
    env:
      REST_PORT: ${{ secrets.REST_PORT }}
      xxx3: ${{ secrets.HIBOU_URL }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Check env
        run: echo "REST PORT is $REST_PORT"
      -
        name: Docker Build
        run: docker-compose up --build -d