name: docker-deploy
run-name: ${{ github.actor }} is deploying with docker
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: production
    env:
      xxx2: ${{ github.environment }}
      xxx3: ${{ github.production }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Check env
        run: echo "environment variables:\n"; env
      -
        name: Docker Build
        run: docker-compose up --build -d