name: docker-deploy
run-name: ${{ github.actor }} is deploying with docker
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: production
    env:
      REST_PORT: ${{ secrets.REST_PORT }}
      PG_PASSWORD: ${{secrets.PG_PASSWORD}}
      HIBOU_URL: ${{secrets.HIBOU_URL}}
      HIBOU_CODE: ${{secrets.HIBOU_CODE}}
      HIBOU_KEY: ${{secrets.HIBOU_KEY}}
      HIBOU_APP: ${{secrets.HIBOU_APP}}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Check env
        run: echo "REST PORT is $REST_PORT"
      -
        name: Docker Build
        run: docker-compose up --build -d