name: docker-deploy
run-name: ${{ github.actor }} is deploying with docker
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker Build
        run: docker-compose up --build -d